# Generated by Django 4.2.4 on 2023-09-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantManagementApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='timings',
            field=models.CharField(max_length=100),
        ),
    ]
